### ISSUE TITLE
Allow debugging from the error handler

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#12]
Using an error handler such as the one used in the Import method is great for user experience. However it can be very painful for development since you cannot jump to the point in execution where the error was raised with the debugger. There is an elegant way to provide this convenience to the developer while still having a nice friendly error message to the user.

A solution is to put a small bit of logic in the error handler which goes a little something like this:

```vb
Sub DoSomething()
    On Error Goto ErrHandler

    ' Actual business logic happens here

ExitProc:
    ' Any clean up code
    Exit Sub

ErrHandler:
    Select Case Err.Number
        Case SomeErrorICanHandle
            ' Handle this error in the best way
        Case Else
            ' For all unhandled errors, crash gracefully.
            UserDecision = ShowCrashPrompt("some message")
            If UserDecision = decision.debug then
                Stop ' This starts the debugger
                Resume ' This causes execution to go back to the line at which the error was raised
            Else
                ' Crash gracefully
            End If
    End Select
End Sub
```

The ShowCrashPrompt doesn't have to be anything fancy. Might be able to get away with a built in dialog type. Just as long as we can get that option of debugging.

If you want the application to have a beautiful dialog then you can create a custom userform. I have done this for a proprietary project before and it turned out quite beautiful. In that example I even provide a diagnostic report that can be sent to a maintainer :)

**Comment by spences10** [comment]
Great 👍 I have no issues with this, I'll check later today.
