### ISSUE TITLE
CustomUI injection

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#16]
Project files may modify the user interface ribbon by having a CustomUI.xml inside the project file (e.g. in the Excel add-in xlam). This CustomUI.xml cannot be edited inside Excel (as far as i know). Instead an xml file is usually injected into the Excel file. The CustomUI.xml can be somewhat generated in Excel by modifying the ribbon manually and then exporting the changes but it is not uncommon to create or modify it using a text editor. Therefore it would be useful to make importing the CustomUI.xml as easy as possible for the same reasons that the VBA source code needs to be easy.

From this [article](https://msdn.microsoft.com/en-us/library/ee767705.aspx), It appears it is possible to inject this CustomUI.xml into the Excel file using VBA. I propose that the add-in should be able to import a CustomUI.xml when the Import button is pressed. I also propose that the CustomUI be unset when the Export button is pressed to prevent the Excel file from becoming out of sync with the CustomUI.xml file.

**Comment by spences10** [comment]
I'll take a look at this later @mattpalermo 

I have been thinking about taking the turn the binary I to a zip, extracting the files manipulate the XML then pack it back up and change the extension back to what it was previously.

You commented on my testing of adding excel XML that it's not a very human readable for diffing so I'm assuming you're aware of this method already.

**Comment by mattpalermo** [comment]
Yes I have already played around with this idea before but I didn't find it useful. As I mentioned in my comment on one of your commits, the [OoXmlUnpack](https://bitbucket.org/htilabs/ooxmlunpack) tool does a really good job of this. If you want, have a play with it and see if you can discover something. But if you want to manipulate a OoXml file, it may be helpful to use a library such as the [Open XML SDK](https://github.com/OfficeDev/Open-XML-SDK), ApachePOI or Openpyxl. These library provide a higher level abstraction for creating and modifying OoXml files. All these methods may be valid ways of injecting CustomUI.xml, however I found that there is a simple function in VBA that could achieve the objective: [SetCustomUI](https://msdn.microsoft.com/en-us/library/office/ff867065.aspx).

**Comment by mattpalermo** [comment]
It appears that the function that I found is not available in Excel and this may not be possible inside the VBA environment. The alternative is to either use existing methods or make a command line program that uses one of the libraries that I mentioned above to inject the CustomUI.xml into the Excel file.

http://stackoverflow.com/questions/16264003/is-there-an-alternative-to-projects-setcustomui-for-excel
http://stackoverflow.com/questions/8850836/how-to-add-a-custom-ribbon-tab-using-vba

**Comment by spences10** [comment]
I'll take a look one day and use something like the in the comments I have made here:

> If you want to create an Excel custom ribbon from scratch and you're not using the CustomUI editor you will need to add the following line to the ```.rels``` file in the ```_rels``` folder

```
<Relationship Id="someID" Type="http://schemas.microsoft.com/office/2006/relationships/ui/extensibility" Target="customUI/customUI.xml"/>
```
