### ISSUE TITLE
Remove alert after import and export?

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#17]
I am not sure that the alert that appears after the import and export is successful is a good user experience. It is a very annoying experience to have to move your mouse point half way across the screen every time to dismiss the dialog. Although, I understand that confirmation feedback is a good thing for user experience.

Any thoughts?

**Comment by mattpalermo** [comment]
I made an experimental branch and removed the prompts to test out if this would be a better experience. Here is the branch: https://github.com/mattpalermo/VBA-IDE-Code-Export/tree/noprompts. I will use this personally for a while to make sure it is better before submitting a PR.

**Comment by spences10** [comment]
I agree @mattpalermo and was thinking the same thing when I was doing the testing the other day, it adds nothing in the way of user experience as you can see visually whats happening in the IDE when you click the menu items.

Submit the PR when you're ready, I'll also merge the dev branch to master now.

`effoff` looks pretty interesting by the way :+1:

**Comment by mattpalermo** [comment]
Submitted PR #18.

The merge sounds appropriate +1

Effoff: thank you I was happy that I managed to get something working in a day :) although I admit it is very unstable at the moment, it should still be useful as long as you don't do anything that it doesn't expect. Still have to take care of error handling, automated testing and of course it needs to be used. I would appreciate any issue that is submitted, even if it is obvious.
