### ISSUE TITLE
Prebuilt add-in

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#27]
A prebuilt add-in or xlsm would really help for those too lazy to build the add-in 😊 .
I think it would be most appropriate to use the Releases feature of github to distribute this.

**Comment by mattpalermo** [comment]
Implemented by release v0.1.0

**Comment by spences10** [comment]
So, should we mention the releases on the README?

**Comment by mattpalermo** [comment]
I put a link in the Installing section. Should it be clearer?

**Comment by spences10** [comment]
No, this is perfectly clear, I obviously didn't read the README! Ha!
