### ISSUE TITLE
Add-in installer

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#28]
An automated installer for the add-in would really help those who are too lazy to install their add-in 😊 .
Issue #27 may be a good first step before achieving this.

From my experience with setting up an installer for [EffOff](https://github.com/mattpalermo/effoff) it can be a bit of a headache. The [Inno installer](http://www.jrsoftware.org/isinfo.php) or the [WiX installer](http://wixtoolset.org) may provide good solutions for this. The NSIS installer scripts seem very verbose, but it seems to be popular on alternativeTo.net.

Or is there a better way to distribute excel add-ins?

**Comment by spences10** [comment]
[Chocolatey](https://chocolatey.org/) :sunglasses: 

Let me have a play around with this today, see if I can come up with something

**Comment by mattpalermo** [comment]
Notes from the other day:
When trying to get EffOff to install on @spences10's work machine, the WiX installer failed at the task. The Inno installer managed perfectly.

**Comment by spences10** [comment]
I tried on another machine with the `effoff VBA-IDE-Code-Export.xlsm` command and got the following output

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.ReadAllText(String path)
   at effoff.effoff.Main(String[] args) in C:\Users\Matthew Palermo\dev\effoff\effoff.cs:line 51
```

**Comment by mattpalermo** [comment]
@spences10 this is simply a bug with EffOff. It has to do with the fact that it wants there to be a "CustomUI" property in the `CodeExport.config.json` file.

**Comment by spences10** [comment]
Just fyi I found this: https://github.com/rubberduck203/VBEX/blob/master/Make.ps1

Again, there's some assumptions here #1 being that you should be admin on your machine to run it, this isn't an option for some users.

I'm not saying CodeExport is a breeze to set up but the instructions are such that you are walked through setup. If the PowerShell script fails for this you are left to pick through the ps1 script for the references.

**Comment by mattpalermo** [comment]
Nice find! This seems like a good example of using development scripts for VBA.

I'm not sure about using a ps script for end user installation. An installer exe seems much more user friendly.
