### ISSUE TITLE
Configuration is not portable

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#4]
The ImportFrom and ExportTo configuration uses absolute file paths. This makes the configuration not portable. The problem is that if I have a project directory with an Excel file and VBA source files which are imported to and exported from the Excel file then I cannot move the project directory without breaking the import/export configuration. I would like to keep the configuration with the project directory because this is a part of the source code - it configures the mapping between VBA files and modules in the Excel file.

When someone clones the project directory, I would like them to be able to import all the files specified in the configuration provided.

**Comment by spences10** [comment]
The .conf file specifies the locations, this was going to be/intended to exporting to a specific location rather than the default which was the 'ThisWorkbook.Path' location previously.

**Comment by mattpalermo** [comment]
That could be quite useful if it allowed for relative paths. I could imagine setting up my VBA source in a sub directory like ./src.

**Comment by mattpalermo** [comment]
Fixed by PR #6
