### ISSUE TITLE
Documentation: Add release instructions

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#41]
Need to document the exact steps for a release so that releases are repeatable.

For the last release I did the following
* Build the Add-In workbook and Add-In
* Created a release through the Releases interface of GitHub. The version number follows [semantic versioning](http://semver.org) in the format "v1.2.3" and the release title follows the format "version 1.2.3".
* Uploaded the Add-In workbook and Add-In as downloads for the release.

There isn't any version numbers in the source code to change... I don't think.

**Comment by spences10** [comment]
No there's nothing in the code in the way of version numbers, I always found that if there isn't a build process that takes care of releases then incrementation gets left out and there then has to be a release to update the version number left from the last release, lol! 

I'm not sure what CI tools we could use for the build of the vba-ide-code export tool, but agree that semantic versioning should be used

**Comment by mattpalermo** [comment]
I don't think there would be any CI tools for us to use since our build involves using Excel and using CodeExport. Unless we created a custom solution, but that seems too much.

**Comment by mattpalermo** [comment]
Closed by PR #65

**Comment by mattpalermo** [comment]
Closed by PR #65
