### ISSUE TITLE
'Releases' and 'Closed pull requests' shields are not working as they should

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#44]
Great work ok the shields @spences10. They look good, but it seems there is a couple of problems to be fixed.

The numbers shown are not the correct numbers. Maybe there is permissions that need to be given shields.io for this to work? Also the 'releases' shield link should point to https://github.com/spences10/VBA-IDE-Code-Export/releases instead of https://github.com/spences10/VBA-IDE-Code-Export

![capture](https://cloud.githubusercontent.com/assets/16647352/22538089/8e1f4c2e-e95b-11e6-8a94-1f8f60c7e20b.PNG)

**Comment by spences10** [comment]
done, badges were derp 😢
