### ISSUE TITLE
Update Repo Description

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#49]
The current repo description is: "Export VBA code from the VBA IDE using the VBComponent class".

I think this should be updated to better summarise the utility of the tool. I think the mention of the VBComponent class is not of immediate interest to a user glancing at the repo trying to determine what the utility can do for them.

Perhaps something like: "Export & Import VBA code. Use Git (or any VCS) for VBA programming."
I'm not 100% sure.

**Comment by spences10** [comment]
That was the first thing that went into the project, no README so I wanted to make it as descriptive as possible.

**Comment by spences10** [comment]
Changed it, take a look, or change it yourself @mattpalermo what do you think?

**Comment by mattpalermo** [comment]
Beautiful :) I totally understand, it wasn't too bad to start with, I am just looking to improve visibility and documentation, and this was an easy target. I don't think I can change it myself. I don't have an "edit" link next to the description or the tags.

**Comment by spences10** [comment]
Really? That's odd, so you can change all the code within but not the title? Strange.

**Comment by mattpalermo** [comment]
I also don't have the settings page, which is kind of expected.

...The title must be a sensitive topic xD

**Comment by spences10** [comment]
I notice it comes up on the hover over the link

**Comment by mattpalermo** [comment]
The world through my eyes (my cursor is over the title but windows thought it would be a great idea to remove my cursor from the screenshot):
![screenshot 6](https://cloud.githubusercontent.com/assets/16647352/22820371/20af54fa-efc2-11e6-9ff6-ab858b1f6a0c.png)

**Comment by spences10** [comment]
Here is where I noticed it, on the traffic tab.

![image](https://cloud.githubusercontent.com/assets/234708/22820571/3edc7d70-ef6f-11e6-9964-82829da57443.png)

Please excuse all the tabs, yes I'm one of those people :+1:

**Comment by mattpalermo** [comment]
That's pretty cool. I guess that's only a taste of what a full [reddit hug of death](http://www.urbandictionary.com/define.php?term=reddit%20hug%20of%20death) is like.
