### ISSUE TITLE
System global state is used for project specific actions

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#5]
The current method for building the files list is `Configure Export` then `Make File List`. The configure export asks the user questions about how the file list should be created, and then stores it in state which is used in any following calls to the `Make File List` action, no matter which project the File List is for. If the user calls the `Make File List` action without calling the `Configure Export` action first, it will use the configuration from the last time the Add-in was used.

To illustrate this problem, if you checkout commit 521e6e9 (the latest commit on master), and then use the Add-in straight away, the ImportFrom and ExportTo fields are populated with the values "C:\Users\spenc\gitrepos\MHC Insight\". I am assuming this a directory in @spences10's computer.

Here is some ideas for how to solve the problem:

Have the user prompted for configuration when `Make File List` is called. Then no state has to be stored in the Excel file at all. It will also make the user's life easier.

For the configuration option currently labelled "List components in 'CondeExportFileList.conf file", the Add-In still has to figure out where the configuration was stored, in a module or in a file. To solve this, there is a few reasonable options I can think of:

* Just search for the module 'modFileList', if that's not found then search for the file 'CodeExportFileList.conf'. (Or the other way around).
* Have the Add-In only use one or the other.

Here is an extreme idea: Don't have any configuration.

I don't see a use for the ImportFrom and ExportTo configuration values. Typically, development of a bunch of interdependent files (like VBA files + Excel file) happens in a project folder where the relative location of these files in the project directory stay the same. However you cannot assume anything about the absolute path of the project folder and therefore relative file paths are most suitable. If we take the KISS approach, we can assume that all the VBA files are in the same directory as the Excel file and then we just need a list of files. See issue #4.

As for the configuration of whether or not to use CodeExportFileList.conf. Always use the config file. A good default is better than configuration. The CodeExportFileList.conf has the advantage over the module of being plain text. If I browse a project directory I can quickly inspect CodeExportFileList.conf with any tool I want (e.g. on github).

**Comment by mattpalermo** [comment]
Just to add to the last paragraph, a down side of CodeExportFileList.conf is that it would not allow to have two CodeExportFileList.confs in one directory. This may not be too difficult to solve though.

**Comment by spences10** [comment]
Thanks for the Input @mattpalermo I am in the process of removing this functionality as it adds no value I was of the two options you suggested going with.

 - Have the Add-In only use one or the other.

The original set up was to have a module left behind listing out what needed to go back in to make up the project but I didn't like how this felt.

Soon after finishing the latest enhancements I realised that there was no need for two option 😕

**Comment by mattpalermo** [comment]
That's good that you feel the same way. Actually, I am just about to push a commit which simplifies the situation. I hope we haven't both done the same thing :*)

**Comment by spences10** [comment]
I think all I have managed was what's in the Dev branch 😌  I look forward to your PR 👍

**Comment by mattpalermo** [comment]
Have a look at https://github.com/mattpalermo/VBA-IDE-Code-Export/tree/noconfig
I will update the README a little bit and then do a PR.

**Comment by spences10** [comment]
Got the PR thanks, my you have been busy 😁 I'll build it and feedback 👍 looks good from my mobile phone screen 🤓

**Comment by mattpalermo** [comment]
Fixed by PR #6
