### ISSUE TITLE
Ribbon UI

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#54]
A ribbon UI which can be used to invoke the actions of CodeExport (import, export, etc) would be very helpful to the UX. Opening the VBE to get at the CodeExport menu is sometimes just too much work. Plus the Ribbon UI is quite stable, pretty, easy to find and easy to use.

To implement this, we could just use one of the tools already available to inject CustomUI.xml into an Excel workbook. Then we would have to save the workbook and commit it to the repo every time the CustomUI.xml was changed. Additionally, the CustomUI.xml couldn't be treated as a text file since it is locked inside the Excel workbook. This may be perfectly OK in the short term, but in the long term it may be ideal to implement a CustomUI.xml injection feature into CodeExport and use it to handle its own CustomUI.xml injection.

**Comment by spences10** [comment]
Resolved with #59
