### ISSUE TITLE
README Improvements

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#63]
Nice work on the README @spences10. It is easy to read and the instructions are very specific. Loving the table of contents as well! I have a few thoughts about further improvements that could be made:

- [x] Move the Usage section above the Build section. Hopefully most users won't need to build the add-in, but will instead just install and go!

- [x] GIFs for the Usage section? I'm not sure if it would be possible to explain it all using a short, audioless gif. Perhaps a YouTube video might be the next step up.
- [x] Update Usage section to mention the new Ribbon UI
- [ ] The manual instructions in the "Add the code" section doesn't instruct the builder to set the VBAProject name. In the `CodeExport.config.json` file, the VBAProject name is declared as `"VBAProject Name": "CodeExport"`.
- [ ] Add Instructions for how to use VBA-IDE-Code-Export to build itself. The instructions in the "Add the code" section describes how to add the code manually. The explanation makes it very clear how to achieve this, but why build it manually when we have created a tool to automatically build things like this? What about, in addition to the manual instructions, also describing the method where you can just use VBA-IDE-Code-Export to build itself automatically?

**Comment by mattpalermo** [comment]
Just remembered this after creating the release:

- [ ] To the build instructions, add a suggestion to set a VBA Project protection password. This stops the add-in from becoming a nuisance in the VBE.

**Comment by spences10** [comment]
Hey @mattpalermo, so I have checked off the video as a 'won't fix', that ok?

The last two points I'm not clear on myself, are there instructions for this?

**Comment by mattpalermo** [comment]
Thanks @spences10, I can take care of the last two points if you'd like and submit a PR for review.

**Comment by spences10** [comment]
Sure thing @mattpalermo I look forward to the PR
