### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by mattpalermo** [spences10/VBA-IDE-Code-Export#64]
I have recently been using this guide lately to keep a clear record of changes: http://keepachangelog.com/en/0.3.0/

It seems to be fairly easy to do. What do you think about it @spences10? Would make for a nice professional touch.

The only non-trivial thing about it would be the release date. I suppose we can just agree to use AEST... I joke, UTC time.

**Comment by spences10** [comment]
😄 yeah, UTC mate 👍 

Where would the log go? OOOO theres a BADGE!! 

Ok, just read the README! Ha! I'll take a look at doing it late today, maybe, I have a ruby environment already set up for my gh pages blog

**Comment by spences10** [comment]
Doh! 06:00 and I hit the close and comment button!!! Sorry, I really should just use the keyboard shortcuts!!

**Comment by spences10** [comment]
Well that could have gone better!

```
bash no command: bundle 
```

**Comment by spences10** [comment]
Set up a machine with this and am just confused as to what to do with it?? 

There's no config to point it to the CodeExport repo when you 

```
rake publish
```

It tries to push it back to the source GitHub repo, I'm so confused

Here's the env if you think you can do anything with it let me know @mattpalermo 

[https://ide.c9.io/spences10/code-export-changelog](https://ide.c9.io/spences10/code-export-changelog)

To run `middleman` you will need to do the following from the command prompt:

```
middleman server $IP -p $PORT
``` 

You will then be able to click the [http://localhost:8080](http://code-export-changelog-spences10.c9users.io:8080/en/0.3.0/) to view the page

Let me know if you can do anything with it

**Comment by mattpalermo** [comment]
Cloud9 wanted my credit card details just to look at your thing. That was mildly annoying so I quit for now. I am not sure what you are doing? I just thought we needed a file in the project directory named `CHANGELOG.md` that contained contents roughly following this example:

```markdown
# Change Log
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/) 
and this project adheres to [Semantic Versioning](http://semver.org/).

## [Unreleased]

- Basked in our Code Export glory

## [0.0.2] - 2014-07-10

- Added beautiful Ribbon UI
- Improved README documentation

## 0.0.1 - 2014-05-31

- Worked magic to create code export

[Unreleased]: https://github.com/spences10/VBA-IDE-Code-Export/compare/v0.2.0...HEAD
[0.2.0]: https://github.com/olivierlacan/VBA-IDE-Code-Export/compare/v0.1.0...v0.2.0
[0.1.0]: https://github.com/spences10/VBA-IDE-Code-Export/tree/v0.1.0
```

This document can be hyperlinked to from the README and release notes.

**Comment by spences10** [comment]
OHSHIT! Sorry buddy!! Some regions want your credit card information... forgot about that, I was reprimanded about that for my Twitter bot too! Apologies again...

**Comment by spences10** [comment]
Hey @mattpalermo I have recently discovered [this](https://github.com/zeit/release)

Could help with the releases, will take a lot of the pain of manually keeping a change log
